server:
  port: 8083
spring:
  datasource:
      name: test
      url: jdbc:mysql://rm-m5epui2mr0l38qot98o.mysql.rds.aliyuncs.com:3306/bzly?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&requireSSL=false
      username: online_db_accout
      password: JdNH9QN52Nd7Pox58J7WmaD5nLiQ
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  activemq: 
      broker-url: tcp://47.105.131.58:61616
      user: admin
      password: admin
      in-memory: true
      pooled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mc.bzly.model

dubbo:
  registry:
    address: 47.105.131.58:2181
#Logger
logging:
  level:
    root: INFO
    com.mc.bzly.dao: trace
    
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: false
    params: count=countSql
    
jedis:
    host: 47.105.131.58
    max:
        idle: 10
        total: 500
        wait:
            millis: 10000
    min:
        idle: 5
    port: 6379
    test:
        'on':
            borrow: true
    zk:
        session:
            timeout:
                ms: 20000